[package]
name = "forth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
# to use `phf` in `no_std` environments
phf = { version = "0.11.2", features = ["macros"] }
